# Test generator for cxxfmt.

# Copyright 2012 Zachary Weinberg <zackw@panix.com>.
# Use, modification, and distribution are subject to the
# Boost Software License, Version 1.0.  See the file LICENSE
# or http://www.boost.org/LICENSE_1_0.txt for detailed terms.

# This Python program generates a C++ program which will test cxxfmt.
# You need to compile its output, compile fmt.cc, link them together,
# and run the result.  The output of that program should be
# self-explanatory.

import generator
import sys

words = [ '', 'i', 'of', 'sis', 'fice', 'drisk', 'elanet', 'hippian',
          'botanist', 'synaptene', 'cipherhood', 'schizognath' ]

aligns = [ '', '<', '>', '^', 'L<', 'R>', 'C^' ]

maxw = len(words) + 3

def output(spec, val):
    spec = '{:' + spec + '}'
    return '"{}", "{}", "{}"'.format(spec, spec.format(val), val)

def g_simple():
    for r in words:
        for a in aligns:
            yield output(a, r)

def g_width():
    for r in words:
        for w in xrange(1, maxw):
            for a in aligns:
                yield output('{}{}'.format(a, w), r)

def g_prec():
    for r in words:
        for p in xrange(maxw):
            for a in aligns:
                yield output('{}.{}'.format(a, p), r)

def g_wnp():
    for r in words:
        for w in xrange(1, maxw):
            for p in xrange(maxw):
                for a in aligns:
                    yield output('{}{}.{}'.format(a, w, p), r)

skeleton_top = r"""// Tester for cxxfmt.

// Copyright 2012 Zachary Weinberg <zackw@panix.com>.
// Use, modification, and distribution are subject to the
// Boost Software License, Version 1.0.  See the file LICENSE
// or http://www.boost.org/LICENSE_1_0.txt for detailed terms.

// This program was generated by test_fmt.py.  DO NOT EDIT.
// Edit test_fmt.py instead.

#ifndef COMPILER_NAME
#define COMPILER_NAME "unknown"
#endif

#include <cstring>
#include <string>
#include <iostream>
#include <fmt.h>

using std::strcmp;
using std::string;
using std::cout;
using std::flush;
using fmt::format;

namespace {

bool quiet = false;

// Note: Plain arrays of POD structures are used because some
// compilers are not yet very good at optimizing std::initializer_list,
// leading to gargantuan assembly output and very slow object file
// generation.

struct case_1arg_s
{
  const char *spec;
  const char *expected;
  const char *val;
};

// more case_ structures here

static bool
report(const char *spec, string const& got, const char *expected)
{
  if (got == expected)
    return true;
  else {
    if (!quiet)
      cout << "\nFAIL: " << spec
           << ": want '" << expected
           << "', got '" << got
           << '\'';
    return false;
  }
}

template <typename case_1arg>
static bool
process(const case_1arg *cases, size_t n)
{
  bool success = true;
  for (const case_1arg *c = cases; c < cases+n; c++) {
    string got(format(c->spec, c->val));
    success &= report(c->spec, got, c->expected);
  }
  return success;
}

// more process_ overloads here

struct i_tblock { virtual bool operator()(const char *) const = 0; };

template <typename case_1arg>
struct tblock : i_tblock
{
  template <size_t N>
  tblock(const char *tag_, const case_1arg (&cases_)[N])
    : tag(tag_), cases(cases_), n(N)
  {}

  virtual bool operator()(const char *label_) const
  {
    string label(label_);
    label += '\t';
    label += tag;
    if (!quiet)
      cout << label << "..." << flush;
    bool success = process(cases, n);
    if (!quiet) {
      if (success)
        cout << " ok\n";
      else
        cout << '\n'; // failures printed already
    }
    return success;
  }

private:
  const char *tag;
  const case_1arg *cases;
  size_t n;
};

"""

skeleton_bot = r"""

} // anonymous namespace

int
main(int argc, char **argv)
{
  if (argc > 1 && !strcmp(argv[1], "-q"))
    quiet = true;
  bool success = true;
  for (size_t i = 0; i < n_tblocks; i++)
    success &= (*tblocks[i])(COMPILER_NAME);
  return success ? 0 : 1;
}
"""

def main(argv):
    if len(argv) > 1:
        outf = open(argv[1], "w")
    else:
        outf = sys.stdout
    with outf:
        gen = generator.TestGenerator()
        gen.add_module('strings', 'case_1arg_s', globals())

        outf.write(skeleton_top)
        gen.generate(outf)
        outf.write(skeleton_bot)

if __name__ == '__main__':
    main(sys.argv)
